/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Agustin
 */
public class Presupuesto extends javax.swing.JFrame {
    private final DataBaseSQL db;
    List<String[]> dataP;
    private boolean isSetProducto;
    /**
     * Creates new form Presupuesto
     */
    public Presupuesto() {
        db = new DataBaseSQL();
        dataP = new ArrayList<>();
        isSetProducto = false;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        productoID = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        desP = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        precioP = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        stockP = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cantP = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        totalP = new javax.swing.JLabel();
        btnElimina = new javax.swing.JLabel();
        btnAgrega = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Presupuesto");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(875, 450));
        setResizable(false);

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel21.setText("Producto");

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel22.setText("ID");

        productoID.setText("0");
        productoID.setToolTipText("");
        productoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoIDActionPerformed(evt);
            }
        });
        productoID.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                actualiza();
            }
            public void removeUpdate(DocumentEvent e) {
                desP.setText("-");
                precioP.setText("0");
                stockP.setText("-");
                totalP.setText("-");
                cantP.setText("-");
                isSetProducto = false;
                //JOptionPane.showMessageDialog(null, "Introduce un id valido");
            }
            public void insertUpdate(DocumentEvent e) {
                actualiza();
            }
            private void actualiza(){
                if( !productoID.getText().matches( "[0-9]*" ) ){
                    isSetProducto = false;
                    JOptionPane.showMessageDialog(null, "Error, El id debe ser un número entero y positivo");
                    return;
                }

                int a = Integer.parseInt(productoID.getText().trim());
                String[] rs;
                rs = db.selectProducto(a);

                if(rs != null){
                    isSetProducto = true;
                    desP.setText(rs[0]);
                    precioP.setText(rs[1]);
                    stockP.setText(rs[2]);
                    cantP.setText("1");
                    totalP.setText(String.valueOf(Float.parseFloat(cantP.getText().trim()) * Float.parseFloat(rs[1])));
                }else{
                    desP.setText("-");
                    precioP.setText("0");
                    stockP.setText("-");
                    totalP.setText("-");
                    cantP.setText("-");
                    isSetProducto = false;
                    if(!productoID.getText().equals("0"))
                    JOptionPane.showMessageDialog(null, "Introduce un id valido");
                }
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel23.setText("Descripción");

        desP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        desP.setText("-");
        desP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        desP.setFocusable(false);
        desP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel25.setText("Precio");

        precioP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        precioP.setText("0");
        precioP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        precioP.setFocusable(false);
        precioP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel27.setText("Stock");

        stockP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stockP.setText("-");
        stockP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        stockP.setFocusable(false);
        stockP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel29.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel29.setText("Cantidad");

        cantP.setText("0");
        cantP.setToolTipText("");
        cantP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantPActionPerformed(evt);
            }
        });
        cantP.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                actualiza();
            }
            public void removeUpdate(DocumentEvent e) {
                // empID.setText("0");
            }
            public void insertUpdate(DocumentEvent e) {
                actualiza();
            }
            private void actualiza(){
                if(stockP.getText().equals("-")){
                    isSetProducto = false;
                    totalP.setText("0");
                    return;
                }
                if( !cantP.getText().matches("[0-9]*") ){
                    isSetProducto = false;
                    totalP.setText("0");
                    JOptionPane.showMessageDialog(null, "Error, Ingrese un número entero y positivo para Cantidad");
                    return;
                }

                if(Integer.parseInt(cantP.getText()) > Integer.parseInt(stockP.getText())){
                    JOptionPane.showMessageDialog(null, "No hay tantos en existencia.");
                    totalP.setText("0");
                    isSetProducto = false;
                    return;
                }
                float a = Float.parseFloat(cantP.getText());
                totalP.setText(String.valueOf(Float.parseFloat(precioP.getText().trim()) * a));
                isSetProducto = true;
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel30.setText("Total");

        totalP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalP.setText("0");
        totalP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        totalP.setFocusable(false);
        totalP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnElimina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N
        btnElimina.setToolTipText("Quitar Producto");
        btnElimina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminaMouseClicked(evt);
            }
        });

        btnAgrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N
        btnAgrega.setText("jLabel33");
        btnAgrega.setToolTipText("Agregar Producto");
        btnAgrega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregaMouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Articulo", "Precio", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        titulo.setText("Generador de Presupuesto");

        jLabel34.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel34.setText("TOTAL:  $");

        total.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        total.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(productoID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel22))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(desP, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel23)))
                                .addComponent(jLabel21))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(108, 108, 108)
                                    .addComponent(jLabel27)
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel30))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(precioP, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel25))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(stockP, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cantP, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(totalP, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(btnAgrega, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(97, 97, 97)
                            .addComponent(titulo))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(titulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desP))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioP))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(stockP)
                                .addComponent(totalP))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAgrega, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoIDActionPerformed

    private void cantPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantPActionPerformed

    private void btnEliminaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminaMouseClicked
        if(jTable2.getSelectedRow() < 0)
        return;

        String a[];
        a = db.selectProducto(Integer.parseInt(dataP.get(jTable2.getSelectedRow())[0]));
        int aux = Integer.parseInt(a[2]) + Integer.parseInt(dataP.get(jTable2.getSelectedRow())[3]);
        db.free("update producto set CANTIDAD = " + String.valueOf( aux ) + " where id = " + dataP.get(jTable2.getSelectedRow())[0]);
        stockP.setText(String.valueOf(aux));
        dataP.remove(jTable2.getSelectedRow());
        productoID.setText("0");
        actualizaTabla();
    }//GEN-LAST:event_btnEliminaMouseClicked

    private void btnAgregaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregaMouseClicked
        if(!isSetProducto)
        return;

        dataP.add(new String[] {
            productoID.getText(),
            desP.getText(),
            precioP.getText(),
            cantP.getText(),
            totalP.getText()
        });
        String a[];
        a = db.selectProducto(Integer.parseInt(productoID.getText()));
        int aux = Integer.parseInt(a[2]) - Integer.parseInt(cantP.getText());
        //db.free("update producto set CANTIDAD = " + String.valueOf(aux) + " where id = " + productoID.getText());
        stockP.setText(String.valueOf(aux));
        productoID.setText("0");
        actualizaTabla();

    }//GEN-LAST:event_btnAgregaMouseClicked
    
    protected void actualizaTabla(){
        int row = 0;
        int cant = dataP.size();
        float totalAux = 0;
        String dat[][] = new String[cant][5];
        
        for(int i = 0; i < cant; i++){
            for(int j = 0; j < 5; j++){
                dat[i][j] = dataP.get(i)[j];
            }
        }
        
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            /*new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            }*/ dat,
            new String [] {
                "ID", "Articulo", "Precio", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        for(int i = 0; i < dataP.size(); i++, row++){
           totalAux += Float.parseFloat(dataP.get(i)[4]);
        }
        total.setText(String.valueOf(totalAux));
        jScrollPane2.setViewportView(jTable2);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presupuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAgrega;
    private javax.swing.JLabel btnElimina;
    private javax.swing.JTextField cantP;
    private javax.swing.JLabel desP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel precioP;
    private javax.swing.JTextField productoID;
    private javax.swing.JLabel stockP;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalP;
    // End of variables declaration//GEN-END:variables
}
