/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Agustin
 */
public final class TicketVenta extends VentasInterface {
    
    private final String folioV;
    HashMap<String, String> datos;
    DataBaseSQL db;
    
    /**
     * Creates new form TicketVenta
     * @param idF
     */
    public TicketVenta(int idF) {
        super();
        initComponents();
        db = new DataBaseSQL();
        folioV = String.valueOf(idF);
        datos = db.fetchArray("venta", Integer.parseInt(folioV));
        titulo.setText("Ticket de Venta");
        disableThings();
        setIDs();
        addDataP();
        super.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void disableThings(){
        jMenuBar1.setVisible(false);
        empID.setEnabled(false);
        cliID.setEnabled(false);
        productoID.setVisible(false);
        cantP.setVisible(false);
        otroPago.setEnabled(false);
        tipoPago.setEnabled(false);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        jLabel25.setVisible(false);
        jLabel27.setVisible(false);
        jLabel29.setVisible(false);
        jLabel30.setVisible(false);
        desP.setVisible(false);
        stockP.setVisible(false);
        precioP.setVisible(false);
        totalP.setVisible(false);
        btnAgrega.setVisible(false);
        btnBorrarTodo.setVisible(false);
        btnElimina.setVisible(false);
        btnGenerarVenta.setVisible(false);
    }    
    public void setIDs(){
        folio.setText(String.valueOf(folioV));
        cliID.setText(datos.get("ID_CLIENTE"));
        empID.setText(datos.get("ID_EMPLEADO"));
        fecha.setText(datos.get("FECHA"));
        
        hora.setText(datos.get("HORA"));
       // total.setText(datos.get("TOTAL"));
        tipoPago.setSelectedItem(datos.get("TIPO_PAGO"));
        otroPago.setText(datos.get("DESC_PAGO"));
        
    }
    
    public void addDataP(){
        List<String[]> datosAux = db.getProductos(folioV);
        HashMap<String, String> datos2;
        
        for (String[] datosAux1 : datosAux) {
            datos2 = db.fetchArray("producto", Integer.parseInt(datosAux1[0]));
            dataP.add(new String[]{datosAux1[0], datos2.get("NOMBRE"), datos2.get("PRECIO"), datosAux1[1], String.valueOf(Float.parseFloat(datosAux1[1]) * Float.parseFloat(datos2.get("PRECIO")))});
        }
        
        actualizaTabla();
    }
    
    /**
     * @param id the command line arguments
     */
    public static void main(int id) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TicketVenta(id).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
