/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2;


import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import java.util.*;

import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.SwingUtilities;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
/**
 *
 * @author Agustin
 */
public class VentasInterface extends javax.swing.JFrame {
    
    private DataBaseSQL db;
    private boolean isSetClient, isSetEmpleado, isSetProducto, areProducts, isSetTipoPago;
    private DateFormat dateFormat;
    private Date date;
    List<String[]> dataP;
    
    /**
     * Creates new form VentasInterface
     */
    public VentasInterface() {
        db = new DataBaseSQL();
        dataP = new ArrayList<>();
        isSetClient = isSetEmpleado = isSetProducto = areProducts = false;
        isSetTipoPago = true;
        initComponents();
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        date = new Date();
        fecha.setText(dateFormat.format(date));
        
        dateFormat = new SimpleDateFormat("HH:mm:ss");
        date = new Date();
        hora.setText(dateFormat.format(date));
        folio.setText(String.valueOf(db.selectID("venta") + 1));

        if("class java2.VentasInterface".equals(this.getClass().toString())){
            otroPagoLbl.setVisible(false);
            otroPago.setVisible(false);
            changeHour();
            addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                eliminaTabla();
                dispose();
            }
            });
        }
        
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        folio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        empID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        empNom = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        empAp = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cliAp = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cliID = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cliNom = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        productoID = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        desP = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        precioP = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        stockP = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cantP = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        totalP = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btnElimina = new javax.swing.JLabel();
        btnAgrega = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        btnGenerarVenta = new javax.swing.JLabel();
        btnBorrarTodo = new javax.swing.JLabel();
        tipoPago = new javax.swing.JComboBox();
        otroPago = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        otroPagoLbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventas JMasters");
        setBounds(new java.awt.Rectangle(10, 10, 900, 620));
        setPreferredSize(new java.awt.Dimension(900, 620));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        titulo.setText("Nueva Venta");

        folio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        folio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        folio.setText("1");
        folio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        folio.setFocusable(false);
        folio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("Folio");

        fecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha.setText("11/11/11");
        fecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fecha.setFocusable(false);
        fecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setText("Fecha");

        hora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hora.setText("11:11:11");
        hora.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        hora.setFocusable(false);
        hora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setText("Hora");

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setText("Empleado");

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setText("ID");

        empID.setText("0");
        empID.setToolTipText("");
        empID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIDActionPerformed(evt);
            }
        });
        empID.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                actualiza();
            }
            public void removeUpdate(DocumentEvent e) {
                isSetEmpleado = false;
                empNom.setText("-");
                empAp.setText("-");
                //JOptionPane.showMessageDialog(null, "Introduce un id valido");

            }
            public void insertUpdate(DocumentEvent e) {
                actualiza();
            }
            private void actualiza(){
                if( !empID.getText().matches( "[0-9]*" ) ){
                    isSetEmpleado = false;
                    JOptionPane.showMessageDialog(null, "Error, El id debe ser un número entero y positivo");
                    return;
                }
                int a = Integer.parseInt(empID.getText().trim());
                //String[] rs;
                HashMap<String, String> rs;
                rs = db.fetchArray("empleado", a);

                if(rs != null){
                    isSetEmpleado = true;
                    empNom.setText(rs.get("NOMBRE"));
                    empAp.setText(rs.get("APELLIDO"));
                }else{
                    isSetEmpleado = false;
                    empNom.setText("-");
                    empAp.setText("-");
                    JOptionPane.showMessageDialog(null, "Introduce un id valido");
                }
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setText("Nombre(s)");

        empNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empNom.setText("-");
        empNom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        empNom.setFocusable(false);
        empNom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel13.setText("Apellidos");

        empAp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empAp.setText("-");
        empAp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        empAp.setFocusable(false);
        empAp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel15.setText("Apellidos");

        cliAp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cliAp.setText("No registrado");
        cliAp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cliAp.setFocusable(false);
        cliAp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel17.setText("Cliente");

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel18.setText("ID");

        cliID.setText("0");
        cliID.setToolTipText("");
        cliID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliIDActionPerformed(evt);
            }
        });
        cliID.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                actualiza();
            }
            public void removeUpdate(DocumentEvent e) {
                isSetClient = false;
                cliNom.setText("-");
                cliAp.setText("-");
                //JOptionPane.showMessageDialog(null, "Introduce un id valido");
            }
            public void insertUpdate(DocumentEvent e) {
                actualiza();
            }
            private void actualiza(){
                if( !cliID.getText().matches( "[0-9]*" ) ){
                    isSetClient = false;
                    JOptionPane.showMessageDialog(null, "Error, El id debe ser un número entero y positivo");
                    return;
                }
                if(cliID.getText().equals("0")){
                    isSetClient = true;
                    cliNom.setText("No registrado");
                    cliAp.setText("No registrado");
                    return;
                }

                int a = Integer.parseInt(cliID.getText().trim());
                //String[] rs;
                HashMap<String, String> rs;
                rs = db.fetchArray("cliente", a);

                if(rs != null){
                    isSetClient = true;
                    cliNom.setText(rs.get("NOMBRE"));
                    cliAp.setText(rs.get("APELLIDO"));
                }else{
                    isSetClient = false;
                    cliNom.setText("-");
                    cliAp.setText("-");
                    JOptionPane.showMessageDialog(null, "Introduce un id valido");
                }
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel19.setText("Nombre(s)");

        cliNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cliNom.setText("No registrado");
        cliNom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cliNom.setFocusable(false);
        cliNom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel21.setText("Producto");

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel22.setText("ID");

        productoID.setText("0");
        productoID.setToolTipText("");
        productoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoIDActionPerformed(evt);
            }
        });
        productoID.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                actualiza();
            }
            public void removeUpdate(DocumentEvent e) {
                desP.setText("-");
                precioP.setText("0");
                stockP.setText("-");
                totalP.setText("-");
                cantP.setText("-");
                isSetProducto = false;
                //JOptionPane.showMessageDialog(null, "Introduce un id valido");
            }
            public void insertUpdate(DocumentEvent e) {
                actualiza();
            }
            private void actualiza(){
                if( !productoID.getText().matches( "[0-9]*" ) ){
                    isSetProducto = false;
                    JOptionPane.showMessageDialog(null, "Error, El id debe ser un número entero y positivo");
                    return;
                }

                int a = Integer.parseInt(productoID.getText().trim());
                //String[] rs;
                HashMap<String, String> rs;
                rs = db.fetchArray("producto", a);

                if(rs != null){
                    isSetProducto = true;
                    desP.setText(rs.get("NOMBRE"));
                    precioP.setText(rs.get("PRECIO"));
                    stockP.setText(rs.get("CANTIDAD"));
                    cantP.setText("1");
                    totalP.setText(String.valueOf(Float.parseFloat(cantP.getText().trim()) * Float.parseFloat(rs.get("PRECIO"))));
                }else{
                    desP.setText("-");
                    precioP.setText("0");
                    stockP.setText("-");
                    totalP.setText("-");
                    cantP.setText("-");
                    isSetProducto = false;
                    if(!productoID.getText().equals("0"))
                    JOptionPane.showMessageDialog(null, "Introduce un id valido");
                }
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel23.setText("Descripción");

        desP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        desP.setText("-");
        desP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        desP.setFocusable(false);
        desP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel25.setText("Precio");

        precioP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        precioP.setText("0");
        precioP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        precioP.setFocusable(false);
        precioP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel27.setText("Stock");

        stockP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stockP.setText("-");
        stockP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        stockP.setFocusable(false);
        stockP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel29.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel29.setText("Cantidad");

        cantP.setText("0");
        cantP.setToolTipText("");
        cantP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantPActionPerformed(evt);
            }
        });
        cantP.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                actualiza();
            }
            public void removeUpdate(DocumentEvent e) {
                // empID.setText("0");
            }
            public void insertUpdate(DocumentEvent e) {
                actualiza();
            }
            private void actualiza(){
                if(stockP.getText().equals("-")){
                    isSetProducto = false;
                    totalP.setText("0");
                    return;
                }
                if( !cantP.getText().matches("[0-9]*") ){
                    isSetProducto = false;
                    totalP.setText("0");
                    JOptionPane.showMessageDialog(null, "Error, Ingrese un número entero y positivo para Cantidad");
                    return;
                }

                if(Integer.parseInt(cantP.getText()) > Integer.parseInt(stockP.getText())){
                    JOptionPane.showMessageDialog(null, "No hay tantos en existencia.");
                    totalP.setText("0");
                    isSetProducto = false;
                    return;
                }
                float a = Float.parseFloat(cantP.getText());
                totalP.setText(String.valueOf(Float.parseFloat(precioP.getText().trim()) * a));
                isSetProducto = true;
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel30.setText("Total");

        totalP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalP.setText("0");
        totalP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        totalP.setFocusable(false);
        totalP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnElimina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N
        btnElimina.setToolTipText("Quitar Producto");
        btnElimina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminaMouseClicked(evt);
            }
        });

        btnAgrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N
        btnAgrega.setText("jLabel33");
        btnAgrega.setToolTipText("Agregar Producto");
        btnAgrega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregaMouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Articulo", "Precio", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTable2);

        jLabel34.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel34.setText("TOTAL:  $");

        total.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        total.setText("0");

        btnGenerarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cobrar.png"))); // NOI18N
        btnGenerarVenta.setToolTipText("Generar Venta");
        btnGenerarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarVentaMouseClicked(evt);
            }
        });

        btnBorrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/borrar.png"))); // NOI18N
        btnBorrarTodo.setToolTipText("Borrar Todo");
        btnBorrarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarTodoMouseClicked(evt);
            }
        });

        tipoPago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipoPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Contado", "Tarjeta", "Anticipo (50%)", "30 dias", "Otro" }));
        tipoPago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoPagoItemStateChanged(evt);
            }
        });
        tipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPagoActionPerformed(evt);
            }
        });

        otroPago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        otroPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otroPagoActionPerformed(evt);
            }
        });
        otroPago.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                actualiza();
            }
            public void removeUpdate(DocumentEvent e) {
                isSetTipoPago = false;
                //JOptionPane.showMessageDialog(null, "Introduce un id valido");

            }
            public void insertUpdate(DocumentEvent e) {
                actualiza();
            }
            private void actualiza(){
                if( otroPago.getText().matches( "-" ) ){
                    isSetTipoPago = false;
                    //JOptionPane.showMessageDialog(null, "Especifica un tipo de pago");
                    return;
                }
                isSetTipoPago = true;
            }
        });

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel24.setText("Tipo de Pago");

        otroPagoLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        otroPagoLbl.setText("Especifica");

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Venta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Nuevo Presupuesto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Agregar Cliente");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Agregar Empleado");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Agregar Producto");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setText("Agregar Stock");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);
        jMenu1.add(jSeparator1);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Buscar Cliente");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Buscar Empleado");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Buscar Producto");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Buscar Venta");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);
        jMenu1.add(jSeparator3);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem4.setText("Ayuda");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Acerca de...");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productoID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(desP, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(precioP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(empNom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(empAp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(stockP, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cantP, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30)
                                            .addComponent(totalP, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAgrega, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(275, 275, 275)
                                        .addComponent(jLabel32))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel4))
                                            .addComponent(folio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel6))
                                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel8))
                                            .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addGap(20, 20, 20))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(cliID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(cliNom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(cliAp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(321, 321, 321))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(otroPagoLbl)
                                    .addComponent(otroPago, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fecha))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hora))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(folio))
                                    .addComponent(titulo))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(empNom)
                                                .addComponent(empAp)))
                                        .addComponent(jLabel13))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cliID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(cliNom)
                                                .addComponent(cliAp))))
                                    .addComponent(jLabel15))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel23)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(43, 43, 43)
                                            .addComponent(cantP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAgrega, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel30))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(stockP)
                                            .addComponent(totalP)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(precioP)
                                .addComponent(desP))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(44, 44, 44)))))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(otroPagoLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(otroPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void empIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIDActionPerformed
            
    }//GEN-LAST:event_empIDActionPerformed

    private void cliIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cliIDActionPerformed

    private void productoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoIDActionPerformed

    private void cantPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantPActionPerformed

    private void btnAgregaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregaMouseClicked
        if(!isSetProducto)
            return;
        
        dataP.add(new String[] {
            productoID.getText(), 
            desP.getText(),
            precioP.getText(),
            cantP.getText(),
            totalP.getText()
        });
        //String a[];
        HashMap<String, String> a;
        a = db.fetchArray("producto", Integer.parseInt(productoID.getText()));
        int aux = Integer.parseInt(a.get("CANTIDAD")) - Integer.parseInt(cantP.getText());
        db.free("update producto set CANTIDAD = " + String.valueOf(aux) + " where id = " + productoID.getText());
        stockP.setText(String.valueOf(aux));
        productoID.setText("0");
        actualizaTabla();
        
    }//GEN-LAST:event_btnAgregaMouseClicked

    private void btnEliminaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminaMouseClicked
        if(jTable2.getSelectedRow() < 0)
            return;
        
        //String a[];
        HashMap<String, String> a;
        a = db.fetchArray("producto", Integer.parseInt(dataP.get(jTable2.getSelectedRow())[0]));
        int aux = Integer.parseInt(a.get("CANTIDAD")) + Integer.parseInt(dataP.get(jTable2.getSelectedRow())[3]);
        db.free("update producto set CANTIDAD = " + String.valueOf( aux ) + " where id = " + dataP.get(jTable2.getSelectedRow())[0]);
        stockP.setText(String.valueOf(aux));
        dataP.remove(jTable2.getSelectedRow());
        productoID.setText("0");
        actualizaTabla();
    }//GEN-LAST:event_btnEliminaMouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Cliente.main(null);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Empleado.main(null);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Producto.main(null);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void btnGenerarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarVentaMouseClicked
        if(!(isSetClient && isSetEmpleado && areProducts && isSetTipoPago)){
            JOptionPane.showMessageDialog(null, "Favor de llenar todos los campos");
            return;
        }
        
        String q;
        q = "insert into venta values(null, '";
        q += cliID.getText() + "', '";
        q += empID.getText() + "', '";
        q += fecha.getText() + "', '";
        q += hora.getText() + "', '";
        q += total.getText() + "', ";
        q += String.valueOf(tipoPago.getSelectedIndex() + 1 ) + ", '";
        q += otroPago.getText();
        q+= "')";
        
        
        //System.out.println(q);
        db.free(q);
        String q2;
        
        for (String[] dataP1 : dataP) {
            q2 = "insert into desc_venta values(" + folio.getText() + ", " + dataP1[0] + ", " + dataP1[3] + ")";
            //System.out.println(q2);
            db.free(q2);
        }
        TicketVenta.main(Integer.parseInt(folio.getText()));
    }//GEN-LAST:event_btnGenerarVentaMouseClicked

    private void btnBorrarTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarTodoMouseClicked
        eliminaTabla();
        setVisible(false);
        VentasInterface.main(null);
        dispose();
    }//GEN-LAST:event_btnBorrarTodoMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        eliminaTabla();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void tipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoPagoActionPerformed

    private void otroPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otroPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otroPagoActionPerformed

    private void tipoPagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoPagoItemStateChanged
        if(!String.valueOf(tipoPago.getSelectedItem()).equals("Otro")){
            isSetTipoPago = true;
            otroPago.setText("NULL");
            otroPagoLbl.setVisible(false);
            otroPago.setVisible(false);
        }else{
            isSetTipoPago = false;
            otroPago.setText("-");
            otroPagoLbl.setVisible(true);
            otroPago.setVisible(true);
        }
    }//GEN-LAST:event_tipoPagoItemStateChanged

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        ProductoBusqueda.main(null);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        EmpleadoBusqueda.main(null);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        ClienteBusqueda.main(null);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
       VentaBusqueda.main(null);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Presupuesto.main(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        Stock.main(null);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        AcercaDe.main(null);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void changeHour(){
       
            new Thread(() -> {
                while (true){
                    SwingUtilities.invokeLater(() -> {
                        dateFormat = new SimpleDateFormat("HH:mm:ss");
                        date = new Date();
                        hora.setText(dateFormat.format(date));
                    });
                    try { Thread.sleep(1000); } catch(Exception e) {}
                }
            }).start();
        
    }
    
    protected void actualizaTabla(){
        int row = 0;
        int cant = dataP.size();
        float totalAux = 0;
        String dat[][] = new String[cant][5];
        
        if(cant <= 0){
            areProducts = false;
           // return;
        }
        
        areProducts = true;
        for(int i = 0; i < cant; i++){
            for(int j = 0; j < 5; j++){
                dat[i][j] = dataP.get(i)[j];
            }
        }
        
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            /*new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            }*/ dat,
            new String [] {
                "ID", "Articulo", "Precio", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        for(int i = 0; i < dataP.size(); i++, row++){
           totalAux += Float.parseFloat(dataP.get(i)[4]);
        }
        total.setText(String.valueOf(totalAux));
        jScrollPane2.setViewportView(jTable2);
    }
    
    public void eliminaTabla(){
        while(!dataP.isEmpty()){
            //String a[];
            HashMap<String, String> a;
            a = db.fetchArray("producto", Integer.parseInt(dataP.get(0)[0]));
            int aux = Integer.parseInt(a.get("CANTIDAD")) + Integer.parseInt(dataP.get(0)[3]);
            db.free("update producto set CANTIDAD = " + String.valueOf( aux ) + " where id = " + dataP.get(0)[0]);
            stockP.setText(String.valueOf(aux));
            dataP.remove(0);
            productoID.setText("0");
            actualizaTabla();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentasInterface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel btnAgrega;
    protected javax.swing.JLabel btnBorrarTodo;
    protected javax.swing.JLabel btnElimina;
    protected javax.swing.JLabel btnGenerarVenta;
    protected javax.swing.JTextField cantP;
    private javax.swing.JLabel cliAp;
    protected javax.swing.JTextField cliID;
    private javax.swing.JLabel cliNom;
    protected javax.swing.JLabel desP;
    private javax.swing.JLabel empAp;
    protected javax.swing.JTextField empID;
    private javax.swing.JLabel empNom;
    protected javax.swing.JLabel fecha;
    protected javax.swing.JLabel folio;
    protected javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    protected javax.swing.JLabel jLabel21;
    protected javax.swing.JLabel jLabel22;
    protected javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    protected javax.swing.JLabel jLabel25;
    protected javax.swing.JLabel jLabel27;
    protected javax.swing.JLabel jLabel29;
    protected javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    protected javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTable jTable2;
    protected javax.swing.JTextField otroPago;
    protected javax.swing.JLabel otroPagoLbl;
    protected javax.swing.JLabel precioP;
    protected javax.swing.JTextField productoID;
    protected javax.swing.JLabel stockP;
    protected javax.swing.JComboBox tipoPago;
    protected javax.swing.JLabel titulo;
    protected javax.swing.JLabel total;
    protected javax.swing.JLabel totalP;
    // End of variables declaration//GEN-END:variables
}
